[2017-07-19 04:57:07,018: INFO/MainProcess] Connected to redis://localhost:6379//
[2017-07-19 04:57:07,035: INFO/MainProcess] mingle: searching for neighbors
[2017-07-19 04:57:08,066: INFO/MainProcess] mingle: all alone
[2017-07-19 04:57:08,091: WARNING/MainProcess] /home/ags/anaconda3/envs/fbbot/lib/python3.5/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2017-07-19 04:57:08,092: INFO/MainProcess] celery@Schrodinger ready.
[2017-07-19 04:57:12,300: INFO/MainProcess] Received task: bot.tasks.completeProfile[40d4e6e3-019d-445d-a4d1-86dd5c280698]  
[2017-07-19 04:57:12,312: INFO/PoolWorker-3] sending msg Oops!, you got me wrong, retry entering it correctly..

And you gotta register first, we'll chat afterwards. :)
if you're facing issues contact https://m.me/rishabh.ags
[2017-07-19 04:57:12,938: INFO/PoolWorker-3] {"error":{"message":"(#10) Cannot message users who are not admins, developers or testers of the app until pages_messaging permission is reviewed and the app is live.","type":"OAuthException","code":10,"error_subcode":2018028,"fbtrace_id":"FJDYHM33Paw"}}
[2017-07-19 04:57:12,940: INFO/PoolWorker-3] Task bot.tasks.completeProfile[40d4e6e3-019d-445d-a4d1-86dd5c280698] succeeded in 0.6363402309998492s: True
[2017-07-19 05:00:00,134: INFO/MainProcess] Received task: crawl_tpo[97cd50d6-1f29-416b-a844-aa8641cad137]  
[2017-07-19 05:00:00,138: INFO/PoolWorker-1] Crawling TPO
[2017-07-19 05:00:05,126: INFO/PoolWorker-1] Crawling Done
[2017-07-19 05:00:05,127: INFO/PoolWorker-1] Task crawl_tpo[97cd50d6-1f29-416b-a844-aa8641cad137] succeeded in 4.988696003998484s: None
